//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradingCommentary {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Problems")]
        public string ProblemsSheetName {
            get {
                return ((string)(this["ProblemsSheetName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Students")]
        public string StudentsSheetName {
            get {
                return ((string)(this["StudentsSheetName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>rubric</string>
  <string>display</string>
  <string>rubrics</string>
  <string>displays</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DisplayTypeField {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DisplayTypeField"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#")]
        public char ProblemSeparator {
            get {
                return ((char)(this["ProblemSeparator"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ID")]
        public string IdField {
            get {
                return ((string)(this["IdField"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Total</string>
  <string>Points</string>
  <string>Point</string>
  <string>Pts</string>
  <string>Pt</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TotalField {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TotalField"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=\"{0}\";Extended Properties=\"Excel 12" +
            ".0 Xml;HDR=YES;IMEX=1;ImportMixedTypes=TEXT\"")]
        public string ExcelConnectionString {
            get {
                return ((string)(this["ExcelConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Description</string>
  <string>Descriptions</string>
  <string>Reference</string>
  <string>References</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DescriptionField {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DescriptionField"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Feedback to Learner")]
        public string CommentHeader {
            get {
                return ((string)(this["CommentHeader"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Feedback Format")]
        public string CommentFormatHeader {
            get {
                return ((string)(this["CommentFormatHeader"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HTML")]
        public string CommentFormat {
            get {
                return ((string)(this["CommentFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Note")]
        public string Note {
            get {
                return ((string)(this["Note"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Total")]
        public string Total {
            get {
                return ((string)(this["Total"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<Display xmlns:xsi=\"http://www.w3.org/20" +
            "01/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <Display" +
            "Setting Name=\"Table\" Default=\"true\">\r\n    <Header>&lt;b&gt;Raw score:&lt;/b&gt; " +
            "{0}.&lt;table&gt;&lt;tr&gt;&lt;th&gt;No.&lt;/th&gt;&lt;th&gt;Points&lt;/th&gt;&l" +
            "t;th&gt;{1}&lt;/th&gt;&lt;th&gt;&lt;/th&gt;&lt;/tr&gt;</Header>\r\n    <Footer>&lt" +
            ";/table&gt;</Footer>\r\n    <RatioBody>&lt;tr style=\"vertical-align:top\"&gt;&lt;th" +
            "&gt;{0}&lt;/th&gt;&lt;td&gt;{1}&lt;/td&gt;&lt;td&gt;{3}&lt;/td&gt;&lt;td&gt;&lt;" +
            "i&gt;{2:0.##%} of the score.&lt;/i&gt; &lt;code&gt;{4}&lt;/code&gt;&lt;/td&gt;&l" +
            "t;/tr&gt;</RatioBody>\r\n    <Body>&lt;tr style=\"vertical-align:top\"&gt;&lt;th&gt;" +
            "{0}&lt;/th&gt;&lt;td&gt;{1}&lt;/td&gt;&lt;td&gt;{3}&lt;/td&gt;&lt;td&gt;&lt;code" +
            "&gt;{4}&lt;/code&gt;&lt;/td&gt;&lt;/tr&gt;</Body>\r\n    <Note>&lt;tr style=\"verti" +
            "cal-align:top\"&gt;&lt;th&gt;{0}&lt;/th&gt;&lt;td colspan=\"3\"&gt;{1}&lt;/td&gt;&l" +
            "t;/tr&gt;</Note>\r\n  </DisplaySetting>\r\n  <DisplaySetting Name=\"Inline\" Default=\"" +
            "false\">\r\n    <Header>&lt;p style=\"{2}\"&gt;&lt;b&gt;Raw score:&lt;/b&gt; {0}. &lt" +
            ";b&gt;{1}:&lt;/b&gt;&lt;br /&gt;</Header>\r\n    <Footer>&lt;/p&gt;</Footer>\r\n    " +
            "<RatioBody>&lt;b&gt;&lt;u&gt;[{0}]&lt;/u&gt;:&lt;/b&gt; {1} penalty, or &lt;i&gt" +
            ";{2:0.##%} of the score&lt;/i&gt;. ({3}). &lt;code&gt;{4}&lt;/code&gt;</RatioBod" +
            "y>\r\n    <Body>&lt;b&gt;&lt;u&gt;[{0}]&lt;/u&gt;:&lt;/b&gt; {1} ({3}). &lt;code&g" +
            "t;{4}&lt;/code&gt;</Body>\r\n    <Note>&lt;b&gt;&lt;u&gt;[{0}]&lt;/u&gt;:&lt;/b&gt" +
            ";. {2}</Note>\r\n  </DisplaySetting>\r\n</Display>")]
        public global::GradingCommentary.Code.DisplayAdapterSettingCollection Display {
            get {
                return ((global::GradingCommentary.Code.DisplayAdapterSettingCollection)(this["Display"]));
            }
        }
    }
}
